Interactive K-RVEA
industrial-optimization-group/desdeo-tools pull request #27
Opened 2021-08-28 14:41 UTC by ppouyaa

I have added the model management in the utilities folder and added a notebook example

2021-08-30 21:44 UTC, light-weaver requested changes

2021-08-30 21:44 UTC, light-weaver commented on desdeo_tools/utilities/model_management.py
> +from desdeo_problem.surrogatemodels.SurrogateModels import GaussianProcessRegressor
desdeo-tools should not depend on methods from desdeo-problem. If you need to use code from both repositories, implement these algorithms in desdeo-emo.

2021-08-30 21:44 UTC, light-weaver commented on desdeo_tools/utilities/model_management.py
> +def ikrvea_mm(reference_point, evolver , problem, u: int) -> float:
Do you need the evolver at all? You never use the EA methods. Instead, you only use the objective/decision/uncertainity vectors.

2021-08-30 21:44 UTC, light-weaver commented on desdeo_tools/utilities/model_management.py
> +def remove_duplicate(X, archive_x):
What's X and archive_x?

2021-08-30 21:44 UTC, light-weaver commented on desdeo_tools/utilities/model_management.py
> +    """ Computes the additive epsilon-indicator between reference front and current approximating front.
Outdated docstring

2021-08-30 21:44 UTC, light-weaver commented on desdeo_tools/utilities/model_management.py
> +    asf_solutions = SimpleASF([1,1,1]).__call__(non_duplicate_obj, reference_point)
This only works for 3D?

2021-09-03 08:47 UTC, ppouyaa commented
I will move it to desdeo_emo

2021-09-03 11:07 UTC, closed without merging